In [139]:
import pandas as pd

df = pd.read_csv("hotel_bookings.csv")

In [140]:
df.shape

(119390, 32)

In [141]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [142]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 29.1+ MB

In [143]:
df.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

In [144]:
df.duplicated().sum()

np.int64(31994)

In [145]:
df["is_canceled"].value_counts()

is_canceled
0    75166
1    44224
Name: count, dtype: int64

In [146]:
df["is_canceled"].value_counts(normalize=True) * 100

is_canceled
0    62.958372
1    37.041628
Name: proportion, dtype: float64

In [147]:
df.describe()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119386.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,103050.000000,6797.000000,119390.000000,119390.000000,119390.000000,119390.000000
mean,0.370416,104.011416,2016.156554,27.165173,15.798241,0.927599,2.500302,1.856403,0.103890,0.007949,0.031912,0.087118,0.137097,0.221124,86.693382,189.266735,2.321149,101.831122,0.062518,0.571363
std,0.482918,106.863097,0.707476,13.605138,8.780829,0.998613,1.908286,0.579261,0.398561,0.097436,0.175767,0.844336,1.497437,0.652306,110.774548,131.655015,17.594721,50.535790,0.245291,0.792798
min,0.000000,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6.000000,0.000000,-6.380000,0.000000,0.000000
25%,0.000000,18.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,62.000000,0.000000,69.290000,0.000000,0.000000
50%,0.000000,69.000000,2016.000000,28.000000,16.000000,1.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,179.000000,0.000000,94.575000,0.000000,0.000000
75%,1.000000,160.000000,2017.000000,38.000000,23.000000,2.000000,3.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,229.000000,270.000000,0.000000,126.000000,0.000000,1.000000
max,1.000000,737.000000,2017.000000,53.000000,31.000000,19.000000,50.000000,55.000000,10.000000,10.000000,1.000000,26.000000,72.000000,21.000000,535.000000,543.000000,391.000000,5400.000000,8.000000,5.000000

In [148]:
df.describe(include="object")

,hotel,arrival_date_month,meal,country,market_segment,distribution_channel,reserved_room_type,assigned_room_type,deposit_type,customer_type,reservation_status,reservation_status_date
count,119390,119390,119390,118902,119390,119390,119390,119390,119390,119390,119390,119390
unique,2,12,5,177,8,5,10,12,3,4,3,926
top,City Hotel,August,BB,PRT,Online TA,TA/TO,A,A,No Deposit,Transient,Check-Out,2015-10-21
freq,79330,13877,92310,48590,56477,97870,85994,74053,104641,89613,75166,1461

In [149]:
pd.crosstab(df["reservation_status"], df["is_canceled"])

is_canceled             0      1
reservation_status
Canceled                0  43017
Check-Out           75166      0
No-Show                 0   1207

In [150]:
df[(df["adults"] == 0) & (df["children"] == 0) & (df["babies"] == 0)].shape

(180, 32)

In [151]:
df[df["adr"] < 0]

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
14969,Resort Hotel,0,195,2017,March,10,5,4,6,2,...,No Deposit,273.0,NaN,0,Transient-Party,-6.38,0,0,Check-Out,2017-03-15

In [152]:
df[df["adr"] > 1000][["hotel", "adr", "adults", "children", "is_canceled"]]

            hotel     adr  adults  children  is_canceled
48515  City Hotel  5400.0       2       0.0            1

In [153]:
print(df["hotel"].unique())
print(df["meal"].unique())
print(df["market_segment"].unique())
print(df["distribution_channel"].unique())
print(df["deposit_type"].unique())
print(df["customer_type"].unique())

['Resort Hotel' 'City Hotel']
['BB' 'FB' 'HB' 'SC' 'Undefined']
['Direct' 'Corporate' 'Online TA' 'Offline TA/TO' 'Complementary' 'Groups'
 'Undefined' 'Aviation']
['Direct' 'Corporate' 'TA/TO' 'Undefined' 'GDS']
['No Deposit' 'Refundable' 'Non Refund']
['Transient' 'Contract' 'Transient-Party' 'Group']

In [154]:
df[["reservation_status_date", "is_canceled"]].head(10)

  reservation_status_date  is_canceled
0              2015-07-01            0
1              2015-07-01            0
2              2015-07-02            0
3              2015-07-02            0
4              2015-07-03            0
5              2015-07-03            0
6              2015-07-03            0
7              2015-07-03            0
8              2015-05-06            1
9              2015-04-22            1

In [155]:
df.nlargest(10, "adults")[["hotel", "adults", "children", "babies", "is_canceled"]]

             hotel  adults  children  babies  is_canceled
2173  Resort Hotel      55       0.0       0            1
1643  Resort Hotel      50       0.0       0            1
1539  Resort Hotel      40       0.0       0            1
1917  Resort Hotel      27       0.0       0            1
1962  Resort Hotel      27       0.0       0            1
1587  Resort Hotel      26       0.0       0            1
1752  Resort Hotel      26       0.0       0            1
1884  Resort Hotel      26       0.0       0            1
2003  Resort Hotel      26       0.0       0            1
2164  Resort Hotel      26       0.0       0            1

In [156]:
df["arrival_date_year"].value_counts().sort_index()

arrival_date_year
2015    21996
2016    56707
2017    40687
Name: count, dtype: int64

In [157]:
df["arrival_date_month"].value_counts()

arrival_date_month
August       13877
July         12661
May          11791
October      11160
April        11089
June         10939
September    10508
March         9794
February      8068
November      6794
December      6780
January       5929
Name: count, dtype: int64

### Initial Data Audit Summary

- The dataset contains 119,390 bookings and 32 columns.
- The target variable is `is_canceled`. Around 63% of bookings were not cancelled and 37% were cancelled.
- Missing values were found in `children`, `country`, `agent` and `company`, with `company` having the most missing values.
- There are 31,994 exact duplicate rows.
- 180 bookings have no adults, children or babies recorded.
- Some unusual numerical values were found, including an ADR of -6.38 and an extreme ADR of 5400.
- `reservation_status` directly reveals whether a booking was cancelled, while `reservation_status_date` contains information about the final booking outcome. Both would cause data leakage.
- `assigned_room_type`, `booking_changes` and `days_in_waiting_list` may contain information that is only known after the booking is initially made, so these will also not be used as predictors.
- Some large guest counts and other extreme values will be investigated before deciding whether they should be removed.
- The prediction is intended to be made using information available when the booking is initially made. Features that are only known after this point should not be used because they could cause data leakage.

In [158]:
df_clean = df.copy()

In [159]:
df_clean = df.copy()

df_clean = df_clean.drop(columns=[
    "reservation_status",
    "reservation_status_date",
    "assigned_room_type",
    "booking_changes",
    "days_in_waiting_list"
])

df_clean.shape

(119390, 27)

In [160]:
df_clean = df_clean.drop(columns=["company"])

df_clean.shape

(119390, 26)

The missing `children` values will be handled later as part of the preprocessing pipeline. This allows the imputation value to be learned from the training data only.

In [161]:
df_clean["country"] = df_clean["country"].fillna("Unknown")

df_clean["country"].isnull().sum()

np.int64(0)

In [162]:
df_clean["agent"].describe()

count    103050.000000
mean         86.693382
std         110.774548
min           1.000000
25%           9.000000
50%          14.000000
75%         229.000000
max         535.000000
Name: agent, dtype: float64

In [163]:
df_clean["agent"] = df_clean["agent"].fillna(0)
df_clean["agent"] = df_clean["agent"].astype(int).astype(str)

df_clean["agent"].isnull().sum()

np.int64(0)

In [164]:
df_clean.isnull().sum()

hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          4
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
deposit_type                      0
agent                             0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
dtype: int64

In [165]:
df_clean = df_clean[
    (df_clean["adults"] + df_clean["children"].fillna(0) + df_clean["babies"]) > 0
]

df_clean.shape

(119210, 26)

In [166]:
df_clean.duplicated().sum()

np.int64(34048)

### Duplicate Rows

Exact duplicate rows were identified during the data audit. These were not removed because the dataset does not contain a unique booking identifier, so identical rows may represent separate bookings rather than data errors.

In [167]:
df_clean.duplicated().sum()

np.int64(34048)

In [168]:
df_clean["is_canceled"].value_counts()

is_canceled
0    75011
1    44199
Name: count, dtype: int64

In [169]:
df_clean["is_canceled"].value_counts(normalize=True) * 100

is_canceled
0    62.923412
1    37.076588
Name: proportion, dtype: float64

### Data Cleaning

- `reservation_status` and `reservation_status_date` were removed because they contain information about the final booking outcome. `assigned_room_type`, `booking_changes` and `days_in_waiting_list` were also removed because they may contain information that is not available when the booking is initially made.
- Removed `company` because around 94% of its values were missing.
- The 4 missing children values are handled using median imputation in the preprocessing pipeline.
- Missing `country` values were labelled as `Unknown`.
- Missing `agent` values were replaced with 0 to represent no recorded agent.
- Removed 180 records where the total number of guests was zero.
- 32,246 identical rows were found but were not removed because the dataset does not contain a unique booking identifier, so they may represent separate bookings.
- After cleaning, the dataset contains 119,210 rows and 26 columns.
- After cleaning, 62.92% of bookings were not cancelled and 37.08% were cancelled.

In [170]:
X = df_clean.drop(columns=["is_canceled"])
y = df_clean["is_canceled"]

print(X.shape)
print(y.shape)

(119210, 25)
(119210,)

In [171]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(X_train.shape)
print(X_test.shape)

(95368, 25)
(23842, 25)

In [172]:
print(y_train.value_counts(normalize=True) * 100)
print(y_test.value_counts(normalize=True) * 100)

is_canceled
0    62.923622
1    37.076378
Name: proportion, dtype: float64
is_canceled
0    62.922574
1    37.077426
Name: proportion, dtype: float64

In [173]:
numerical_cols = X_train.select_dtypes(include=["int64", "float64"]).columns
categorical_cols = X_train.select_dtypes(include=["object"]).columns

print("Numerical:", len(numerical_cols))
print("Categorical:", len(categorical_cols))

Numerical: 15
Categorical: 10

In [174]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

numerical_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

In [175]:
from sklearn.preprocessing import OneHotEncoder

categorical_transformer = OneHotEncoder(handle_unknown="ignore")

In [176]:
from sklearn.compose import ColumnTransformer

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numerical_transformer, numerical_cols),
        ("cat", categorical_transformer, categorical_cols)
    ]
)

In [177]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

print("Accuracy:", accuracy_score(y_test, baseline_predictions))
print("Precision:", precision_score(y_test, baseline_predictions, zero_division=0))
print("Recall:", recall_score(y_test, baseline_predictions))
print("F1 Score:", f1_score(y_test, baseline_predictions))

Accuracy: 0.6292257360959651
Precision: 0.0
Recall: 0.0
F1 Score: 0.0

In [178]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, baseline_predictions)

array([[15002,     0],
       [ 8840,     0]])

### Train/Test Split and Baseline

The cleaned data was split into 80% training data and 20% test data. Stratification was used so that the proportion of cancelled and non-cancelled bookings remained similar in both sets. A random state of 42 was used so the split can be reproduced.

A majority-class baseline was created using `DummyClassifier`. The baseline always predicts the most common class, which is a non-cancelled booking.

Baseline results:
- Accuracy: 62.92%
- Precision: 0.00
- Recall: 0.00
- F1 Score: 0.00

Although the baseline achieves 62.92% accuracy, it does not identify any cancelled bookings. This shows why accuracy should not be considered on its own for this dataset.

The confusion matrix was [[15002, 0], [8840, 0]]. This confirms that the baseline predicted every booking as non-cancelled and failed to identify any of the 8,840 cancelled bookings.

### Preprocessing Pipeline

A `ColumnTransformer` was used to apply different preprocessing to numerical and categorical features. Missing numerical values are filled using median imputation and numerical features are then standardised using `StandardScaler`. Categorical features are encoded using `OneHotEncoder(handle_unknown="ignore")`.

The preprocessing and baseline classifier were combined in a `Pipeline`. This means the preprocessing is fitted using the training data and then applied consistently to the test data, helping to avoid data leakage.

In [179]:
from sklearn.pipeline import Pipeline

baseline_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", DummyClassifier(strategy="most_frequent"))
])

In [180]:
baseline_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  Index(['lead_time', 'arrival_date_year', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies',
       'is_repeated_gue...
       'previous_bookings_not_canceled', 'adr', 'required_car_parking_spaces',
       'total_of_special_requests'],
      dtype='object')),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index(['hotel', 'arrival_date_month', 'meal', 'country', 'market_segment',
       'distribution_channel', 'reserved_room_type', 'deposit_type', 'agent',
       'customer_type'],
      dtype='object'))])),
                ('classifier', DummyClassifier(strategy='most_frequent'))])

In [181]:
pipeline_predictions = baseline_pipeline.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pipeline_predictions))
print("Precision:", precision_score(y_test, pipeline_predictions, zero_division=0))
print("Recall:", recall_score(y_test, pipeline_predictions))
print("F1 Score:", f1_score(y_test, pipeline_predictions))

Accuracy: 0.6292257360959651
Precision: 0.0
Recall: 0.0
F1 Score: 0.0

In [182]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, pipeline_predictions)

array([[15002,     0],
       [ 8840,     0]])